# Generated by Django 4.2.2 on 2023-06-29 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='Ingresa una descripción breve de la inversión.', max_length=1000)),
                ('company', models.CharField(max_length=200)),
            ],
        ),
    ]
