# Generated by Django 4.2.2 on 2023-06-29 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='date_published',
            field=models.DateField(blank=True, help_text='Fecha de publicación.', null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='company',
            field=models.CharField(help_text='Ingresa el nombre de la compañía que dirige el proyecto.', max_length=200),
        ),
        migrations.AlterField(
            model_name='investment',
            name='title',
            field=models.CharField(help_text='Ingresa el título del proyecto.', max_length=200),
        ),
    ]
