# Generated by Django 4.2.2 on 2023-06-29 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_investment_date_published_alter_investment_company_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Investment',
            new_name='Proyect',
        ),
    ]
