# Generated by Django 4.2.2 on 2023-07-06 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0003_rename_investment_proyect'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyect',
            name='expected_interest_rate',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='proyect',
            name='mini_summary',
            field=models.TextField(default='', help_text='Ingresa una descripción breve de la inversión. No más de 50 carácteres.', max_length=50),
        ),
        migrations.AlterField(
            model_name='proyect',
            name='summary',
            field=models.TextField(help_text='Ingresa una descripción de la inversión.', max_length=1000),
        ),
        migrations.CreateModel(
            name='ProyectInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID único para proyecto', primary_key=True, serialize=False)),
                ('date_acquired', models.DateField(blank=True, help_text='Fecha de unión al proyecto.', null=True)),
                ('date_of_end_contract', models.DateField(blank=True, help_text='Fecha de fin de unión al proyecto.', null=True)),
                ('investment', models.DecimalField(decimal_places=10, max_digits=19)),
                ('investor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('proyect', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.proyect')),
            ],
        ),
    ]
