# Generated by Django 4.2.2 on 2023-07-06 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_proyect_expected_interest_rate_proyect_mini_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyect',
            name='summary',
            field=models.TextField(default='', help_text='Ingresa una descripción de la inversión.', max_length=1000),
        ),
    ]
