# Generated by Django 4.2.2 on 2023-07-06 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_proyect_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectinstance',
            name='investment',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=19),
        ),
    ]
