# Generated by Django 4.2.2 on 2023-07-06 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_proyectinstance_investment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectinstance',
            name='date_acquired',
            field=models.DateField(blank=True, help_text='Fecha de unión al proyecto', null=True),
        ),
        migrations.AlterField(
            model_name='proyectinstance',
            name='date_of_end_contract',
            field=models.DateField(blank=True, help_text='Fecha de fin de unión al proyecto', null=True),
        ),
    ]
