# Generated by Django 4.2.2 on 2023-07-06 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_proyectinstance_prubea'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProyectInstance',
        ),
    ]
