# Generated by Django 4.2.2 on 2023-07-06 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0009_delete_proyectinstance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID único para proyecto', primary_key=True, serialize=False)),
                ('date_acquired', models.DateField(blank=True, help_text='Fecha de unión al proyecto', null=True)),
                ('date_of_end_contract', models.DateField(blank=True, help_text='Fecha de fin de unión al proyecto', null=True)),
                ('investment', models.DecimalField(decimal_places=10, default=0, max_digits=19)),
                ('prubea', models.DateField(blank=True, help_text='Fecha de unión al proyecto', null=True)),
                ('investor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('proyect', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.proyect')),
            ],
        ),
    ]
