# Generated by Django 4.2.2 on 2023-07-06 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_proyectinstance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyectinstance',
            name='prubea',
        ),
    ]
