# Generated by Django 4.2.2 on 2023-07-07 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_remove_proyectinstance_prubea'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyect',
            options={'permissions': (('can_add_proyect', 'Puede añadir proyecto'),)},
        ),
    ]
