# Generated by Django 4.2.2 on 2023-07-07 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_proyect_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyectinstance',
            options={'permissions': (('can_add_instance_proyect', 'Puede añadir inversión'),)},
        ),
    ]
