# Generated by Django 4.2.2 on 2023-07-18 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_proyectinstance_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyect',
            old_name='expected_interest_rate',
            new_name='interest_rate',
        ),
        migrations.AddField(
            model_name='proyectinstance',
            name='rate_time',
            field=models.IntegerField(default=0),
        ),
    ]
